version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend_v2
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend_v2/cred.json:/app/cred.json:ro